POST http://localhost:3001/auth/login/
Content-Type: application/json
{
  "email": "NatLane@email.com",
  "password": "Password1!"
}

POST http://localhost:3001/auth/signup/
Content-Type: application/json
{
  "firstName": "Natalie",
  "lastName": "Lane",
  "email": "NatLane@email.com",
  "password": "Password1!"
}

POST http://localhost:3001/auth/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWFkMzBiYzU3M2FmZmEyNTc0ZTQzN2YiLCJlbWFpbCI6Im5hdGxhbmVAZW1haWwuY29tIiwiaWF0IjoxNzg5NzM2MjEzLCJleHAiOjE3ODk4MjI2MTN9.b0Z9Z8KptKkB3A4LJb7Y1zRk612FwxmKNu8RY6KP-ws