DELETE http://localhost:3001/projects/6a86bf4f077c01359bf5b17f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTg0NWVjMjJjODM4ZmYxNTA1MDc4Y2QiLCJlbWFpbCI6Im5hdGxhbmVAZW1haWwuY29tIiwiaWF0IjoxNzg3MTUwMTgzLCJleHAiOjE3ODcyMzY1ODN9.fbWfgqeTDJ7H2kEd68UGGmHy305uwaGvW5BZwM-SC-4