DELETE http://localhost:3001/projects/6a8c0a9a8f3f6cc3c6dfb580
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTg0NWVjMjJjODM4ZmYxNTA1MDc4Y2QiLCJlbWFpbCI6Im5hdGxhbmVAZW1haWwuY29tIiwiaWF0IjoxNzg3NTYyNjE2LCJleHAiOjE3ODc2NDkwMTZ9.-FRMHRPiPGm6Igk8FHLezM03D4TugxcwyYqhvLvONdw