GET http://localhost:3001/projects?limit=3&page=d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTg0NWVjMjJjODM4ZmYxNTA1MDc4Y2QiLCJlbWFpbCI6Im5hdGxhbmVAZW1haWwuY29tIiwiaWF0IjoxNzg3NDgwOTA2LCJleHAiOjE3ODc1NjczMDZ9.h96Ur_qI8ejttqdtIfwZ9kwakUP-D_CSOaOIyxKocxg