POST http://localhost:3001/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTg0NWVjMjJjODM4ZmYxNTA1MDc4Y2QiLCJlbWFpbCI6Im5hdGxhbmVAZW1haWwuY29tIiwiaWF0IjoxNzg3NTYyNjE2LCJleHAiOjE3ODc2NDkwMTZ9.-FRMHRPiPGm6Igk8FHLezM03D4TugxcwyYqhvLvONdw
{
  "title": "New Title",
  "description": "description",
  "developmentAreas": ["UI", "UX", "API"],
  "environments": ["Windows", "Mac", "Linux", "Google"]
} 