DELETE http://localhost:3001/bugs/6a86dfee2077c2eb8085ece5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTg0NWVjMjJjODM4ZmYxNTA1MDc4Y2QiLCJlbWFpbCI6Im5hdGxhbmVAZW1haWwuY29tIiwiaWF0IjoxNzg3NzU1MzkwLCJleHAiOjE3ODc4NDE3OTB9.eA8y8VHOEGnamORu_Tz7HgCJM48SYptx9sgPkOR0UVo