GET http://localhost:3001/projects/6a86df762077c2eb8085ece/bugs?limit=2&page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTg0NWVjMjJjODM4ZmYxNTA1MDc4Y2QiLCJlbWFpbCI6Im5hdGxhbmVAZW1haWwuY29tIiwiaWF0IjoxNzg4NjAwNTA0LCJleHAiOjE3ODg2ODY5MDR9.ok4VR0N5u-RvxhV_ZLq_92bx2MerKJU1p35bgYW38_I