GET http://localhost:3001/projects/6a86df762077c2eb8085ece0/bugs?limit=2&page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTg0NWVjMjJjODM4ZmYxNTA1MDc4Y2QiLCJlbWFpbCI6Im5hdGxhbmVAZW1haWwuY29tIiwiaWF0IjoxNzg3MjI2MzMyLCJleHAiOjE3ODczMTI3MzJ9.eH3PUUGLYp3_SV-PiGsBQom_gHv8NOozQNcpFCTz2mc