POST http://localhost:3001/projects/6a81f168c3c23c08be0fb5e2/bugs
Content-Type: application/json
{
  "title": "title",
  "developmentArea": "UI",
  "severity": "normal",
  "stepsToReproduce": ["Step 1", "Step 2", "Step 3"],
  "environmentsUsed": ["Mac"],
  "expectedResult": "result",
  "actualResult": "result"
}